[package]
name = "event-packet"
version = "0.0.0"
edition = "2021"
publish = false

[features]
serde = ["dep:serde"]
bincode = ["dep:bincode"]

[dependencies]
bincode = { version = "1", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }

