[package]
name = "ipc-channel"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "1"
bytes = "1"
tokio = { version = "1", features = ["sync", "macros", "rt-multi-thread", "time"] }
thiserror = "1"

[dev-dependencies]
rand = "0.8"

