[package]
name = "crash-reporter"
version = "0.1.0"
edition = "2021"

[lib]
name = "crash_reporter"
path = "src/lib.rs"

[[bin]]
name = "crash-reporter"
path = "src/main.rs"

[dependencies]
# std-only stub

