[package]
name = "permission-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
pref-store = { version = "0.1.0", path = "../pref-store" }
serde = { version = "1", features = ["derive"] }

